version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  redis:
    image: redis
    ports:
      - "6379:6379"

  matchmaker:
    image: optimuscloud/match-maker
    ports:
      - "6898:6898"

  mdb:
    image: optimuscloud/mdb
    ports:
      - "9099:9099"

  akira:
    image: optimuscloud/akira
    ports:
      - "6889:6889"
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - matchmaker

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  optimusServices:
    image: testvagrant/optimus-services
    ports:
      - "8090:8090"
    restart: always
    depends_on:
        - mongo

  optimusDashboard:
    image: testvagrant/optimusdashboard
    ports:
      - "9901:9900"
    environment:
      - DE_ENV=production
      - DB_SERVER_URL=mongo:27017
      - DB_NAME=optimus?authSource=admin
    restart: always
    depends_on:
        - mongo
